name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Install Deps
      run: go mod tidy

    - name: Build
      run: go run main.go
    
    - name: Run tests
      run: |
        cd tests/
        go test

  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Install Deps
      run: go mod tidy

    - name: Build
      run: go run main.go

    - name: Run tests
      run: |
        cd tests/
        go test